---
title: "Gail Score from Facebook - Analysis"
author: "Divya Narayanan"
date: "September 26, 2016"
output: html_document
---
### Project: Gail Score from Facebook

### Background

The Gail Score is a risk assessment tool to quantify a woman's risk for developing invasive breast cancer. Certain factors, such as age, race, and ancestral history can be indicative of future development. Based on a woman's Facebook profile, this model aims to quantify the risk of invasive breast cancer. For further information, see <http://www.cancer.gov/bcrisktool>. The tool provided utilizes the following variables to make a prediction: 

* Medical history of breast cancer or previous radiation therapy
* Mutation of either BRCA1 or BRCA2 gene
* Woman's age (>35)
* Age at time of first menstrual cycle
* How many first-degree relatives have breast cancer?
* Prior breast biopsy
* Race/ethnicity

### Question Development
#### General Question

What information from a woman's Facebook profile is most indicative of her risk for developing breast cancer, as calculated by the Gail Score? 

#### Concrete Question 

Based on a random sample of public profiles in the US, how can I weight characteristics derived from a woman's Facebook profile and other sources to calculate the Gail Score and infer the risk of developing breast cancer? 

### Description of the Data and Method

Information utilized by the tool above may not be directly stated on a profile. However, it could be obtained by data-scraping statuses posted by the individual, page likes, or past/future events the individual has or will attend. A potential dataset would be profiles scraped from Facebook of women over the age of 35 in the US. Thresholds and methods would have to be developed to determine if liking a page (e.g. Susan G. Komen Organization) or using certain words in a status is indicative of any of the criteria mentioned above. 

### Updates Since 9/20/2016
* Downloaded sample dataset of 750 posts (easy to increase size)
    + Posts/comments from Susan G. Komen FB page (largest breast cancer organization in the US)
    + Cleaned to extract public users based on error message
        * Removed observations that are organizations or not individuals 
    + Used gender package to determine gender of remaining individuals based on US SSA between 1930 and 2012
        * Excluded individuals where name was not recognized 
    + Used wru package to predict race/ethnicity of remaining individuals
* Started with downloading of 750 posts/comments
    + Yielded cleaned dataset of 139 women 

### Updates Since 9/13/2016
* Created app through Facebook API
    + Obtained token from Facebook OAuth
* Downloaded Rfacebook package from CRAN/Github (Pablo Barbera)
    + Use access token for authentication in R 

### Current Issues
* Not all the information needed to calculate the Gail score can be derived from a Facebook profile
* Creating a lot of data -- is there a limit to this? 
    + What proxies can be used for extremely personal/sensitive variables?

### Plan for Upcoming Week
* Obtain a larger dataset [around 5000 posts]
* Draw data from distributions for age at menarche 
* What other variables to look at based on existing model? 