---
title: "GailScore_Final"
author: "Divya Narayanan"
date: "October 10, 2016"
output: html_document
---

### Title: Estimating the Gail Score from Facebook 

### Introduction

The Gail Score is a risk assessment tool to quantify a woman's risk for developing invasive breast cancer [1]. Based on data from the American Cancer Society, nearly 200,000 women are diagnosed with breast cancer every year [2]. Fortunately, the screening rate of invasive breast cancer cases has been on the rise and plateaued since the late 1980's [3]. Certain risk factors, such as age, race, and ancestral history can be indicative of future development. The Gail Model, or Breast Cancer Risk Assessment Tool, as it has been modified, was originally validated for use on white women age 35 and older. In recent years, the tool has been modified to account for women of other ethnicities [1].

Despite the national attention on breast cancer awareness, many individuals may not be aware of their risk for developing breast cancer or realize that their personal and familial characteristics could put them at higher risk. This analysis wanted to look at what information obtained from a woman's Facebook profile could be used to determine a potential risk of developing breast cancer, as calculated by the Gail model. Based on a random sample of public Facebook profiles, we looked solely at their age and racial background to estimate their 5-year risk of developing breast cancer. 

### Question Development
#### General Question

What information from a woman's Facebook profile is most indicative of her risk for developing breast cancer, as calculated by the Gail Score? 

#### Concrete Question  

Based on a random sample of public profiles in the US, how can characteristics derived from a woman's Facebook profile and other sources be weighted to calculate the Gail Score and infer the risk of developing breast cancer? 

* Medical history of breast cancer or previous radiation therapy
* Mutation of either BRCA1 or BRCA2 gene
* Woman's age (>35)
* Age at time of first menstrual cycle
* How many first-degree relatives have breast cancer?
* Prior breast biopsy
* Race/ethnicity

### Methods

Much of the information requested by the current Gail model, such as history of breast cancer, mutation of BRCA1 or BRCA2 gene, or prior breast biopsy, is rarely available on public Facebook profiles. However, for the purposes of our analysis, these risk factors were simply left as unknown, and were accounted for as such in calculation of the Gail Score. 

Posts and comments were scraped from the Susan G. Komen Organization (SGK) Facebook page, representing one of the largest breast cancer organization in the US. These data were obtained by interacting with the Facebook API through the `Rfacebook` package. With the hopes of yielding a fairly large sample size, the 2500 most recent posts and comments from the page were scraped on Sunday, October 3, 2016. From this data, individuals were classifed as public or private users based on access to basic demographic information. 

Once public users were identified, names were extracted into first and last name variables to determine the genders and races of the individuals. These were determined based on first and last names, respectively, with predictions from the `gender` and `wru` packages, respectively.To determine the ages of individuals, data from the Social Security Administration between 1930 and 2015 was utilized. Since age of an individual was not made public through data scraping, age was estimated to be the median age of individuals with a given first name and appropriate variability estimates were obtained.

#### Data

Scraping of the 2500 comments and posts yielded 1539 unique public users who posted to the Susan G. Komen page. Of these 1539 individuals, 549 were female. Further subsetting by age, 305 of these women were age 35 and above. Below are the racial and age distributions of the women in the analytic sample:   

```{r echo = FALSE}
source("6_DataandFigures.R")
```

### References 
1. https://www.cancer.gov/bcrisktool/about-tool.aspx#gail
2. http://www.cancer.org/acs/groups/content/documents/image/acspc-043955.pdf

### Updates since 10/04/2016

### Updates Since 9/27/2016
* "Full", cleaned dataset now of age > 35, race, gender predictions
* Analysis plan
    + Extract coefficients from BRCAT source code (in C) based on mostly unknown situations
    + calculate Gail Score prediction 
    + Estimates of variability (best way to do this?)
* Questions 
    + How to make ID code run faster
    + Code in Rmd

### Limitations
The current Gail Score Tool is an 8-question tool that based on characteristics, such as age, race, mutation in a BRCA1/2 gene, among others. Often times, even for individuals with public Facebook profiles, it's not possible to extract all this information. Much of this data will come from other publicly available sources, such as SSA data, or through race and gender prediction packages in R.   

### Updates Since 9/20/2016
* Downloaded sample dataset of 750 posts (easy to increase size)
    + Posts/comments from Susan G. Komen FB page (largest breast cancer organization in the US)
    + Cleaned to extract public users based on error message
        * Removed observations that are organizations or not individuals 
    + Used gender package to determine gender of remaining individuals based on US SSA between 1930 and 2012
        * Excluded individuals where name was not recognized 
    + Used wru package to predict race/ethnicity of remaining individuals
* Started with downloading of 750 posts/comments
    + Yielded cleaned dataset of 139 women 

### Updates Since 9/13/2016
* Created app through Facebook API
    + Obtained token from Facebook OAuth
* Downloaded Rfacebook package from CRAN/Github (Pablo Barbera)
    + Use access token for authentication in R 
